DROP FUNCTION IF EXISTS isCmpmsExist;
DELIMITER $$
CREATE FUNCTION isCmpmsExist() RETURNS INT(1)
BEGIN
	IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cmpms') = 0 THEN
		RETURN 0;
	ELSE
		RETURN 1;
	END IF;
    
END $$
DELIMITER ;